# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDesigner-ContrastThickness_scalable.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1175, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Image4K_Tab = QtWidgets.QWidget()
        self.Image4K_Tab.setObjectName("Image4K_Tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Image4K_Tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.processing_hlayout = QtWidgets.QHBoxLayout()
        self.processing_hlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.processing_hlayout.setObjectName("processing_hlayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_dir_hlayout = QtWidgets.QHBoxLayout()
        self.input_dir_hlayout.setObjectName("input_dir_hlayout")
        self.input_dir_select_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.input_dir_select_btn.setObjectName("input_dir_select_btn")
        self.input_dir_hlayout.addWidget(self.input_dir_select_btn)
        self.input_dir_display = QtWidgets.QLineEdit(self.Image4K_Tab)
        self.input_dir_display.setReadOnly(True)
        self.input_dir_display.setObjectName("input_dir_display")
        self.input_dir_hlayout.addWidget(self.input_dir_display)
        self.verticalLayout_2.addLayout(self.input_dir_hlayout)
        self.file_management_hlayout = QtWidgets.QHBoxLayout()
        self.file_management_hlayout.setObjectName("file_management_hlayout")
        self.file_list_label = QtWidgets.QLabel(self.Image4K_Tab)
        self.file_list_label.setObjectName("file_list_label")
        self.file_management_hlayout.addWidget(self.file_list_label)
        self.file_manage_btns_hlayout = QtWidgets.QHBoxLayout()
        self.file_manage_btns_hlayout.setObjectName("file_manage_btns_hlayout")
        self.checkBox = QtWidgets.QCheckBox(self.Image4K_Tab)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.file_manage_btns_hlayout.addWidget(self.checkBox)
        self.remove_files_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.remove_files_btn.setObjectName("remove_files_btn")
        self.file_manage_btns_hlayout.addWidget(self.remove_files_btn)
        self.refresh_files_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.refresh_files_btn.setObjectName("refresh_files_btn")
        self.file_manage_btns_hlayout.addWidget(self.refresh_files_btn)
        self.file_management_hlayout.addLayout(self.file_manage_btns_hlayout)
        self.verticalLayout_2.addLayout(self.file_management_hlayout)
        self.file_tableView = QtWidgets.QTableView(self.Image4K_Tab)
        self.file_tableView.setObjectName("file_tableView")
        self.verticalLayout_2.addWidget(self.file_tableView)
        self.file_filter_text = QtWidgets.QLineEdit(self.Image4K_Tab)
        self.file_filter_text.setText("")
        self.file_filter_text.setObjectName("file_filter_text")
        self.verticalLayout_2.addWidget(self.file_filter_text)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.processing_hlayout.addLayout(self.verticalLayout)
        self.image_vlayout = QtWidgets.QVBoxLayout()
        self.image_vlayout.setSpacing(6)
        self.image_vlayout.setObjectName("image_vlayout")
        self.image_settings_vlayout = QtWidgets.QVBoxLayout()
        self.image_settings_vlayout.setObjectName("image_settings_vlayout")
        self.img_settings_title_hlayout = QtWidgets.QHBoxLayout()
        self.img_settings_title_hlayout.setObjectName("img_settings_title_hlayout")
        self.label_4 = QtWidgets.QLabel(self.Image4K_Tab)
        self.label_4.setObjectName("label_4")
        self.img_settings_title_hlayout.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.img_settings_save_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.img_settings_save_btn.setObjectName("img_settings_save_btn")
        self.img_settings_title_hlayout.addWidget(self.img_settings_save_btn, 0, QtCore.Qt.AlignRight)
        self.img_settings_load_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.img_settings_load_btn.setObjectName("img_settings_load_btn")
        self.img_settings_title_hlayout.addWidget(self.img_settings_load_btn, 0, QtCore.Qt.AlignRight)
        self.image_settings_vlayout.addLayout(self.img_settings_title_hlayout)
        self.img_settings_tabWidget = QtWidgets.QTabWidget(self.Image4K_Tab)
        self.img_settings_tabWidget.setObjectName("img_settings_tabWidget")
        self.rgb_tab = QtWidgets.QWidget()
        self.rgb_tab.setObjectName("rgb_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rgb_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hlayout_2 = QtWidgets.QHBoxLayout()
        self.hlayout_2.setObjectName("hlayout_2")
        self.hlayout_3 = QtWidgets.QHBoxLayout()
        self.hlayout_3.setObjectName("hlayout_3")
        self.vlayout = QtWidgets.QVBoxLayout()
        self.vlayout.setObjectName("vlayout")
        self.label_6 = QtWidgets.QLabel(self.rgb_tab)
        self.label_6.setObjectName("label_6")
        self.vlayout.addWidget(self.label_6)
        self.grayscale_slider_r = QtWidgets.QSlider(self.rgb_tab)
        self.grayscale_slider_r.setMaximum(255)
        self.grayscale_slider_r.setProperty("value", 255)
        self.grayscale_slider_r.setSliderPosition(255)
        self.grayscale_slider_r.setOrientation(QtCore.Qt.Vertical)
        self.grayscale_slider_r.setObjectName("grayscale_slider_r")
        self.vlayout.addWidget(self.grayscale_slider_r)
        self.hlayout_3.addLayout(self.vlayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.rgb_tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.grayscale_slider_g = QtWidgets.QSlider(self.rgb_tab)
        self.grayscale_slider_g.setMaximum(255)
        self.grayscale_slider_g.setProperty("value", 255)
        self.grayscale_slider_g.setSliderPosition(255)
        self.grayscale_slider_g.setOrientation(QtCore.Qt.Vertical)
        self.grayscale_slider_g.setObjectName("grayscale_slider_g")
        self.verticalLayout_9.addWidget(self.grayscale_slider_g)
        self.hlayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.rgb_tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.grayscale_slider_b = QtWidgets.QSlider(self.rgb_tab)
        self.grayscale_slider_b.setMaximum(255)
        self.grayscale_slider_b.setProperty("value", 255)
        self.grayscale_slider_b.setSliderPosition(255)
        self.grayscale_slider_b.setOrientation(QtCore.Qt.Vertical)
        self.grayscale_slider_b.setObjectName("grayscale_slider_b")
        self.verticalLayout_8.addWidget(self.grayscale_slider_b)
        self.hlayout_3.addLayout(self.verticalLayout_8)
        self.hlayout_2.addLayout(self.hlayout_3)
        self.grayscale_vlayout = QtWidgets.QVBoxLayout()
        self.grayscale_vlayout.setObjectName("grayscale_vlayout")
        self.label_9 = QtWidgets.QLabel(self.rgb_tab)
        self.label_9.setObjectName("label_9")
        self.grayscale_vlayout.addWidget(self.label_9)
        self.grayscale_img_preview = QtWidgets.QGraphicsView(self.rgb_tab)
        self.grayscale_img_preview.setObjectName("grayscale_img_preview")
        self.grayscale_vlayout.addWidget(self.grayscale_img_preview)
        self.hlayout_2.addLayout(self.grayscale_vlayout)
        self.verticalLayout_6.addLayout(self.hlayout_2)
        self.img_settings_tabWidget.addTab(self.rgb_tab, "")
        self.background_tab = QtWidgets.QWidget()
        self.background_tab.setObjectName("background_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.background_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hlayout = QtWidgets.QHBoxLayout()
        self.hlayout.setObjectName("hlayout")
        self.groupBox = QtWidgets.QGroupBox(self.background_tab)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 160, 213))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bkgnd_rb_mode = QtWidgets.QRadioButton(self.layoutWidget)
        self.bkgnd_rb_mode.setObjectName("bkgnd_rb_mode")
        self.verticalLayout_4.addWidget(self.bkgnd_rb_mode)
        self.bkgnd_rb_median = QtWidgets.QRadioButton(self.layoutWidget)
        self.bkgnd_rb_median.setObjectName("bkgnd_rb_median")
        self.verticalLayout_4.addWidget(self.bkgnd_rb_median)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.bkgnd_rb_rgb = QtWidgets.QRadioButton(self.layoutWidget)
        self.bkgnd_rb_rgb.setObjectName("bkgnd_rb_rgb")
        self.verticalLayout_17.addWidget(self.bkgnd_rb_rgb)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.rgb_value_display = QtWidgets.QLineEdit(self.layoutWidget)
        self.rgb_value_display.setReadOnly(True)
        self.rgb_value_display.setObjectName("rgb_value_display")
        self.horizontalLayout_16.addWidget(self.rgb_value_display)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        self.rgb_colour_pick_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.rgb_colour_pick_btn.setObjectName("rgb_colour_pick_btn")
        self.verticalLayout_16.addWidget(self.rgb_colour_pick_btn)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_4.addLayout(self.verticalLayout_17)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.hlayout.addWidget(self.groupBox)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.background_tab)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.background_tab)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_18.addWidget(self.graphicsView_5)
        self.hlayout.addLayout(self.verticalLayout_18)
        self.verticalLayout_7.addLayout(self.hlayout)
        self.img_settings_tabWidget.addTab(self.background_tab, "")
        self.threshold_tab = QtWidgets.QWidget()
        self.threshold_tab.setObjectName("threshold_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.threshold_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.threshold_tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.threshold_lower = QtWidgets.QLineEdit(self.threshold_tab)
        self.threshold_lower.setReadOnly(True)
        self.threshold_lower.setObjectName("threshold_lower")
        self.horizontalLayout_12.addWidget(self.threshold_lower)
        self.threshold_range_widget = QtWidgets.QSlider(self.threshold_tab)
        self.threshold_range_widget.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_range_widget.setObjectName("threshold_range_widget")
        self.horizontalLayout_12.addWidget(self.threshold_range_widget)
        self.threshold_upper = QtWidgets.QLineEdit(self.threshold_tab)
        self.threshold_upper.setReadOnly(True)
        self.threshold_upper.setObjectName("threshold_upper")
        self.horizontalLayout_12.addWidget(self.threshold_upper)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.threshold_tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.threshold_img_preview = QtWidgets.QGraphicsView(self.threshold_tab)
        self.threshold_img_preview.setObjectName("threshold_img_preview")
        self.verticalLayout_5.addWidget(self.threshold_img_preview)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.img_settings_tabWidget.addTab(self.threshold_tab, "")
        self.image_settings_vlayout.addWidget(self.img_settings_tabWidget)
        self.image_vlayout.addLayout(self.image_settings_vlayout)
        self.image_previews = QtWidgets.QHBoxLayout()
        self.image_previews.setObjectName("image_previews")
        self.input_img_vlayout = QtWidgets.QVBoxLayout()
        self.input_img_vlayout.setObjectName("input_img_vlayout")
        self.label_2 = QtWidgets.QLabel(self.Image4K_Tab)
        self.label_2.setObjectName("label_2")
        self.input_img_vlayout.addWidget(self.label_2)
        self.input_img_preview = QtWidgets.QGraphicsView(self.Image4K_Tab)
        self.input_img_preview.setObjectName("input_img_preview")
        self.input_img_vlayout.addWidget(self.input_img_preview)
        self.image_previews.addLayout(self.input_img_vlayout)
        self.output_img_vlayout = QtWidgets.QVBoxLayout()
        self.output_img_vlayout.setObjectName("output_img_vlayout")
        self.label_3 = QtWidgets.QLabel(self.Image4K_Tab)
        self.label_3.setObjectName("label_3")
        self.output_img_vlayout.addWidget(self.label_3)
        self.output_img_preview = QtWidgets.QGraphicsView(self.Image4K_Tab)
        self.output_img_preview.setObjectName("output_img_preview")
        self.output_img_vlayout.addWidget(self.output_img_preview)
        self.image_previews.addLayout(self.output_img_vlayout)
        self.image_vlayout.addLayout(self.image_previews)
        self.processing_hlayout.addLayout(self.image_vlayout)
        self.processing_hlayout.setStretch(0, 3)
        self.processing_hlayout.setStretch(1, 9)
        self.verticalLayout_14.addLayout(self.processing_hlayout)
        self.output_hlayout = QtWidgets.QHBoxLayout()
        self.output_hlayout.setObjectName("output_hlayout")
        self.output_label = QtWidgets.QLabel(self.Image4K_Tab)
        self.output_label.setObjectName("output_label")
        self.output_hlayout.addWidget(self.output_label)
        self.output_folder_hlayout = QtWidgets.QHBoxLayout()
        self.output_folder_hlayout.setObjectName("output_folder_hlayout")
        self.output_folder_select_btn = QtWidgets.QPushButton(self.Image4K_Tab)
        self.output_folder_select_btn.setObjectName("output_folder_select_btn")
        self.output_folder_hlayout.addWidget(self.output_folder_select_btn)
        self.output_folder_display = QtWidgets.QLineEdit(self.Image4K_Tab)
        self.output_folder_display.setReadOnly(True)
        self.output_folder_display.setObjectName("output_folder_display")
        self.output_folder_hlayout.addWidget(self.output_folder_display)
        self.output_hlayout.addLayout(self.output_folder_hlayout)
        self.threshold_options_vlayout = QtWidgets.QHBoxLayout()
        self.threshold_options_vlayout.setObjectName("threshold_options_vlayout")
        self.threshold_enable = QtWidgets.QCheckBox(self.Image4K_Tab)
        self.threshold_enable.setChecked(True)
        self.threshold_enable.setObjectName("threshold_enable")
        self.threshold_options_vlayout.addWidget(self.threshold_enable)
        self.threshold_ifenabled_options = QtWidgets.QVBoxLayout()
        self.threshold_ifenabled_options.setObjectName("threshold_ifenabled_options")
        self.save_distribution_img = QtWidgets.QCheckBox(self.Image4K_Tab)
        self.save_distribution_img.setChecked(True)
        self.save_distribution_img.setObjectName("save_distribution_img")
        self.threshold_ifenabled_options.addWidget(self.save_distribution_img)
        self.save_contrast_img = QtWidgets.QCheckBox(self.Image4K_Tab)
        self.save_contrast_img.setChecked(True)
        self.save_contrast_img.setObjectName("save_contrast_img")
        self.threshold_ifenabled_options.addWidget(self.save_contrast_img)
        self.threshold_options_vlayout.addLayout(self.threshold_ifenabled_options)
        self.output_hlayout.addLayout(self.threshold_options_vlayout)
        self.start_process = QtWidgets.QPushButton(self.Image4K_Tab)
        self.start_process.setEnabled(False)
        self.start_process.setObjectName("start_process")
        self.output_hlayout.addWidget(self.start_process)
        self.verticalLayout_14.addLayout(self.output_hlayout)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        spacerItem2 = QtWidgets.QSpacerItem(20, 762, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.Image4K_Tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.img_settings_tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_dir_select_btn.setText(_translate("MainWindow", "Open Directory..."))
        self.input_dir_display.setPlaceholderText(_translate("MainWindow", "Directory..."))
        self.file_list_label.setText(_translate("MainWindow", "File list:"))
        self.checkBox.setText(_translate("MainWindow", "Inc. Subdir\'s"))
        self.remove_files_btn.setText(_translate("MainWindow", "Remove Selected"))
        self.refresh_files_btn.setText(_translate("MainWindow", "Refresh from Dir."))
        self.file_filter_text.setPlaceholderText(_translate("MainWindow", "Filter files..."))
        self.label_4.setText(_translate("MainWindow", "Global Settings"))
        self.img_settings_save_btn.setText(_translate("MainWindow", "Save Settings"))
        self.img_settings_load_btn.setText(_translate("MainWindow", "Load Settings"))
        self.label_6.setText(_translate("MainWindow", "Red"))
        self.label_8.setText(_translate("MainWindow", "Green"))
        self.label_7.setText(_translate("MainWindow", "Blue"))
        self.label_9.setText(_translate("MainWindow", "Grayscale Image:"))
        self.img_settings_tabWidget.setTabText(self.img_settings_tabWidget.indexOf(self.rgb_tab), _translate("MainWindow", "RGB to Grayscale"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Background:"))
        self.bkgnd_rb_mode.setText(_translate("MainWindow", "Mode"))
        self.bkgnd_rb_median.setText(_translate("MainWindow", "Median"))
        self.bkgnd_rb_rgb.setText(_translate("MainWindow", "Custom RGB"))
        self.label_14.setText(_translate("MainWindow", "rgb"))
        self.rgb_colour_pick_btn.setText(_translate("MainWindow", "Colour Picker"))
        self.label_15.setText(_translate("MainWindow", "Contrast Image Preview"))
        self.img_settings_tabWidget.setTabText(self.img_settings_tabWidget.indexOf(self.background_tab), _translate("MainWindow", "Background and Contrast"))
        self.label_11.setText(_translate("MainWindow", "Threshold Range"))
        self.label_10.setText(_translate("MainWindow", "Contrast Distribution"))
        self.img_settings_tabWidget.setTabText(self.img_settings_tabWidget.indexOf(self.threshold_tab), _translate("MainWindow", "Thresholding"))
        self.label_2.setText(_translate("MainWindow", "Image Input Preview"))
        self.label_3.setText(_translate("MainWindow", "Image Output Preview"))
        self.output_label.setText(_translate("MainWindow", "Output:"))
        self.output_folder_select_btn.setText(_translate("MainWindow", "Select"))
        self.output_folder_display.setPlaceholderText(_translate("MainWindow", "Output folder..."))
        self.threshold_enable.setText(_translate("MainWindow", "Thresholding Enabled"))
        self.save_distribution_img.setText(_translate("MainWindow", "Save Contrast Distribution"))
        self.save_contrast_img.setText(_translate("MainWindow", "Save Contrast Image"))
        self.start_process.setText(_translate("MainWindow", "Start Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image4K_Tab), _translate("MainWindow", "Images (<4K)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
